services:

  speech_to_text:
    build: ./speech_to_text
    container_name: speech_to_text
    hostname: speech_to_text
    ports:
      - "5000:5000"
    restart: on-failure:3
    devices:
      - "/dev/snd"
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    stdin_open: true
    tty: true
    volumes:
      - ./speech_to_text:/app
    networks:
      - speak_io_net

  text_to_speech:
    build: ./text_to_speech
    container_name: text_to_speech
    hostname: text_to_speech
    ports:
      - "5500:5500"
    restart: on-failure:3
    devices:
      - "/dev/snd"
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    stdin_open: true
    tty: true
    volumes:
      - ./text_to_speech:/app
    networks:
      - speak_io_net

  voice_ui:
    build: ./voice_ui
    container_name: voice_ui
    hostname: voice_ui
    restart: on-failure:3
    ports:
      - "5700:5700"
    depends_on:
      - speech_to_text
      - text_to_speech
    networks:
      - speak_io_net

networks:
  speak_io_net:
    driver: bridge
